from pathlib import Path

# The provider activity is generated by upgrade_intelligence_ui.py. Normalize its
# LinearLayout padding call and imports after generation.
p=Path('app/src/main/java/com/astra/ai/AstraProviderActivity.kt')
if p.exists():
    s=p.read_text(encoding='utf-8')
    s=s.replace('padding(22)', 'setPadding(22,22,22,22)')
    s=s.replace('.padding(22)', '.setPadding(22,22,22,22)')
    p.write_text(s,encoding='utf-8')

p=Path('app/src/main/java/com/astra/ai/LiveAgentSession.kt')
s=p.read_text(encoding='utf-8')
if 'import kotlinx.coroutines.cancel' not in s:
    s=s.replace('import kotlinx.coroutines.Job\n','import kotlinx.coroutines.Job\nimport kotlinx.coroutines.cancel\n')
p.write_text(s,encoding='utf-8')
assert 'cancel' in s
